project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Application of LIME and SHAP to Credit Scoring Models"
  author:
    - Ruoqi Li (rl3489)
    - Yibing Liu (yl5714)
  repo-url: https://github.com/ruoqili0612/prof-copy
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - chap1.qmd
    - chap2.qmd
    - conclusion.qmd

format:
  html:
    theme: null
    css: styles/bootstrap.min.css
    code-fold: true


